<div class="container-fluid">
    <div class="doctors" style="margin-bottom: 30px">
        <div class="col-md-3">
            <div class="circle-color color-1">
                <h5> Петров П.Г. (кабинет - 404)</h5>
            </div>
        </div>
        <div class="col-md-3">
            <div class="circle-color color-2">
                <h5> Ткачук Д.Р. (кабинет - 404)</h5>
            </div>
        </div>
        <div class="col-md-3">
            <div class="circle-color color-3">
                <h5> Климентьев В.Г. (кабинет - 404)</h5>
            </div>
        </div>
        <div class="col-md-3">
            <div class="circle-color color-4">
                <h5> Другое</h5>
            </div>
        </div>
    </div>

    <div class="dhx_cal_container panel" id="scheduler_here">
        <div class="dhx_cal_navline">
            <div class="dhx_cal_prev_button">&nbsp;</div>
            <div class="dhx_cal_next_button">&nbsp;</div>
            <div class="dhx_cal_today_button"></div>
            <div class="dhx_cal_date"></div>
            <div class="dhx_minical_icon" id="dhx_minical_icon" onclick="AgereCommunicator.show_minical()">&nbsp;</div>
            <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
            <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
            <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
        </div>
        <div class="dhx_cal_header"></div>
        <div class="dhx_cal_data"></div>
    </div>
</div>